AllCops:
  DisplayCopNames: true

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/EndOfLine:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
