sudo: false
language: ruby
cache:
  - bundler
os:
  - linux
  - osx
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 1f0d32b3520856e69d94369434090c1bac6ec4ebbcbc772c7d88555de0a1e814
