language: ruby
cache:
  - bundler
os:
  - linux
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler
