# Use the new container-based Travis infrastructure.
sudo: false

language: ruby
cache:
  - bundler

script:
  - bundle exec rake

os:
  - linux
  - osx

rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_failure: always
